config/routes.rb
LibrarySchedule::Application.routes.draw do

  root :to => "pages#home"

  resources :sessions, :only => [:new, :create, :destroy]
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
  match '/login/preauth', :to => 'sessions#preauth'

  scope '/admin' do
    resources :users, :except => [:edit]
    post '/users/:user_id', :to => "users#change_password"

    resources :schools, :except => [:edit]

    resources :from_methods, :except => [:edit]
  end

  scope '/manage' do
    resources :lists, :except => [:edit]
    resources :groups, :except => [:edit]
  end

  resources :recipients

  

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :recipients
  has_many :message_permissions, :as => :object, :dependent => :destroy
  has_many :message_recipients, :as => :object, :dependent => :destroy

  validates :name, :presence => true,
                   :uniqueness => {:case_sensitive => false}
  validates :user_id, :presence => true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  authorize_resource

  def index
    @groups = Group.order(:name)
    @title = "Groups"
  end

  def new
    @group = Group.new()
    @title = "Create New Group"
  end

  def create
    @group = current_user.groups.build(params[:group])
    if @group.save
      #group created
      flash[:success] = "Group '#{@group.name}' successfully created."
      redirect_to groups_path
    else
      #there was an error
      @title = "Create New Group"
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
    @title = "Group Detail"
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      flash[:success] = "Group '#{@group.name}' updated."
      redirect_to groups_path
    else
      @title = "Group Detail"
      render :show
    end
  end

  def destroy
    group = Group.find(params[:id]).destroy
    flash[:notice] = "Group '#{group.name}' deleted."
    redirect_to groups_path
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_group_form.html.haml
= form_for(@group) do |f|
  = render 'shared/error_messages', :object => f.object
  %fieldset
    %legend Basic Info
    %div.form-field
      = f.label :name, :class => "required"
      = f.text_field :name
  %div.form-submit
    = f.submit "#{op} Group"

app/views/groups/index.html.haml
%div#user-actions.round
  %p= link_to("Create New Group", new_group_path)
%ul#groups-list.no-list-style
  - @groups.each do |group|
    %li= link_to group.name, group

app/views/groups/new.html.haml
%p.back-link= link_to "Back", groups_path
= render 'group_form', :op => 'Create'

app/views/groups/show.html.haml
%p.back-link= link_to "Back", groups_path
= render 'group_form', :op => 'Edit'
%p.form-delete-link= link_to("Delete Group", @group, :method => 'delete', :confirm => 'Are you sure you want to delete this group?  This can not be undone.')