config/routes.rb
LibrarySchedule::Application.routes.draw do

  root :to => "pages#home"

  resources :sessions, :only => [:new, :create, :destroy]
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
  match '/login/preauth', :to => 'sessions#preauth'

  scope '/admin' do
    resources :users, :except => [:edit]
    post '/users/:user_id', :to => "users#change_password"

    resources :schools, :except => [:edit]

    resources :from_methods, :except => [:edit]
  end

  scope '/manage' do
    resources :lists, :except => [:edit]
    resources :groups, :except => [:edit]
  end

  resources :recipients

  

end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  has_and_belongs_to_many :groups
  has_many :contact_methods
  has_many :linked_recipients, :foreign_key => "parent_id",
                               :dependent => :destroy
  has_many :reverse_linked_recipients, :foreign_key => "student_id",
                                       :class_name => "LinkedRecipient",
                                       :dependent => :destroy
  has_many :parents, :through => :reverse_linked_recipients
  has_many :students, :through => :linked_recipients
  has_and_belongs_to_many :schools
  belongs_to :recipient_type
  has_many :message_recipients, :as => :object, :dependent => :destroy

  validates :external_id, :presence => true,
                          :uniqueness => {:scope => :recipient_type_id, :case_sensitive => false}
  validates :recipient_type_id, :presence => true
  validates :first_name, :presence => true
  validates :last_name, :presence => true

  def add_parent!(parent)
    self.reverse_linked_recipients.create!(:parent_id => parent.id) if parent.is_parent? && self.is_student?
  end

  def add_student!(student)
    self.linked_recipients.create!(:student_id => student.id) if student.is_student? && self.is_parent?
  end

  def is_student?
    self.recipient_type.name == 'Student'
  end

  def is_parent?
    self.recipient_type.name == 'Parent'
  end

  def is_staff?
    self.recipient_type.name == 'Staff'
  end

  def contacts(message_type, contact_method_types)
    contacts = Array.new
    # Get our own contact methods
    self.contact_methods.each do |contact_method|
      delivery_option = contact_method.delivery_options.own.for_message_type(message_type)
      contacts.push contact_method if (!delivery_option.empty? || message_type.name == 'emergency') && contact_method_types.include?(contact_method.contact_method_type.name)
    end
    # Get the parents contact methods
    self.parents.each do |parent|
      parent.contact_methods.each do |contact_method|
        delivery_option = contact_method.delivery_options.linked(self.id).for_message_type(message_type)
        contacts.push contact_method if (!delivery_option.empty? || message_type.name == 'emergency') && contact_method_types.include?(contact_method.contact_method_type.name)
      end
    end
    return contacts
  end
end

app/models/recipient_type.rb
class RecipientType < ActiveRecord::Base
  has_many :recipients, :dependent => :destroy
  has_many :message_permissions, :as => :object, :dependent => :destroy
  has_many :message_recipients, :as => :object, :dependent => :destroy

  validates :name, :presence => true, :uniqueness => {:case_sensitive => false}
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  authorize_resource

  def index
    @title = "Recipients"
    @recipients = Recipient.all
  end

  def new
    @recipient = Recipient.new()
    @title = "Create New Recipient"
  end

  def create
    @recipient = Recipient.new(params[:recipient])
    if @recipient.save
      #recipient created
      flash[:success] = "Recipient successfully created."
      redirect_to recipient_path(@recipient)
    else
      #there was an error
      @title = "Create New Recipient"
      render :new
    end
  end

  def show
    @recipient = Recipient.find(params[:id])
    @title = "Recipient Detail"
  end

  def edit
    @recipient = Recipient.find(params[:id])
    @title = "Edit Recipient"
  end

  def update
    @recipient = Recipient.find(params[:id])
    if @recipient.update_attributes(params[:recipient])
      # Save the Parent/Student Links
      params[:recipient_parents] = Array.new if params[:recipient_parents].nil?
      params[:recipient_students] = Array.new if params[:recipient_students].nil?
      @recipient.parent_ids = params[:recipient_parents]
      @recipient.student_ids = params[:recipient_students]
      flash[:success] = "Recipient updated."
      redirect_to recipient_path(@recipient)
    else
      @title = "Edit Recipient"
      render :edit
    end
  end

  def destroy
    recipient = Recipient.find(params[:id]).destroy
    flash[:notice] = "Recipient deleted."
    redirect_to recipients_path
  end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/_recipient_form.html.haml
= form_for(@recipient) do |f|
  = render 'shared/error_messages', :object => f.object
  %fieldset
    %legend Basic Info
    %div.form-field
      = f.label :recipient_type_id, "Type", :class => "required"
      = f.select :recipient_type_id, options_from_collection_for_select(RecipientType.all, 'id','name', @recipient.recipient_type_id)
    %div.form-field
      = f.label :first_name, "First Name", :class => "required"
      = f.text_field :first_name
    %div.form-field
      = f.label :last_name, "Last Name", :class => "required"
      = f.text_field :last_name
    %div.form-field
      = f.label :external_id, "External ID", :class => "required"
      = f.text_field :external_id
  %fieldset
    %legend Links
    %table#recipient-links-gui
      %tr
        %td#students
          %div
            - @recipient.students.each do |student|
              %p{:class => 'recipient-link-student', :id => "recipient-link-student-#{student.id}"}
                = "#{student.first_name} #{student.last_name}"
                %span.recipient-link-delete.clickable= image_tag(path_to_image("link_delete.png"))
                = hidden_field_tag "recipient_students[]", student.id, :id => "recipient-link-student-hidden-#{student.id}"
        %td.arrow= image_tag path_to_image "arrow_right_grey.png"
        %td#self
          = image_tag path_to_image("user.png")
          %h5 This Recipient
        %td.arrow= image_tag path_to_image "arrow_right_grey.png"
        %td#parents
          %div
            - @recipient.parents.each do |parent|
              %p{:class => 'recipient-link-parent', :id => "recipient-link-parent-#{parent.id}"}
                = "#{parent.first_name} #{parent.last_name}"
                %span.recipient-link-delete.clickable= image_tag(path_to_image("link_delete.png"))
                = hidden_field_tag "recipient_parents[]", parent.id, :id => "recipient-link-parent-hidden-#{parent.id}"
  %div.form-submit
    = f.submit "#{op} Recipient"

app/views/recipients/edit.html.haml
%p.back-link= link_to "Back", recipient_path(@recipient)
= render 'recipient_form', :op => 'Edit'
%p.form-delete-link= link_to("Delete Recipient", @recipient, :method => 'delete', :confirm => 'Are you sure you want to delete this Recipient?  This can not be undone.')

app/views/recipients/index.html.haml
- if can? :create, Recipient
  %div#user-actions.round
    %p= link_to("Create New Recipient", new_recipient_path)
//TODO Full-fledged gui to find recipients
%ul#recipients-list.no-list-style
  - @recipients.each do |recipient|
    %li= link_to "#{recipient.first_name} #{recipient.last_name}", recipient

app/views/recipients/new.html.haml
%p.back-link= link_to "Back", recipients_path
= render 'recipient_form', :op => 'Create'

app/views/recipients/show.html.haml
//TODO CSS for view-fields & edit link
%p.back-link= link_to "Back", recipients_path
- if can? :edit, @recipient
  %p.edit-link= link_to "Edit Recipient Info", edit_recipient_path(@recipient)
%fieldset
  %legend Basic Info
  %div.view-field
    %p.label Type
    %p.value= @recipient.recipient_type.name
  %div.view-field
    %p.label First Name
    %p.value= @recipient.first_name
  %div.view-field
    %p.label Last Name
    %p.value= @recipient.last_name
  %div.view-field
    %p.label External ID
    %p.value= @recipient.external_id