config/routes.rb
LibrarySchedule::Application.routes.draw do

  root :to => "pages#home"

  resources :sessions, :only => [:new, :create, :destroy]
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
  match '/login/preauth', :to => 'sessions#preauth'

  scope '/admin' do
    resources :users, :except => [:edit]
    post '/users/:user_id', :to => "users#change_password"

    resources :schools, :except => [:edit]

    resources :from_methods, :except => [:edit]
  end

  scope '/manage' do
    resources :lists, :except => [:edit]
    resources :groups, :except => [:edit]
  end

  resources :recipients

  

end

app/models/from_method.rb
class FromMethod < ActiveRecord::Base
  has_and_belongs_to_many :schools
  has_many :delivery_methods

  before_validation :strip_from_method
  before_validation :clean_up_phone

  validates :from_method_type, :presence => true
  validates :from_method, :presence => true,
                          :uniqueness => {:scope => :from_method_type, :case_sensitive => false}
  validates :from_method, :format => {:with => email_regex, :message => "must be a valid email address"}, :if => lambda {|o| o.from_method_type == 'email'}
  validates :from_method, :length => {:is => 11, :message => "must be a valid phone number"}, :numericality => {:only_integer => true, :greater_than => 10000000000, :message => "must be a valid phone number"}, :if => lambda {|o| o.from_method_type == 'phone'}

  def strip_from_method
    self.from_method.strip!
  end

  def clean_up_phone
    self.from_method = self.from_method.computerize_phone_number if self.from_method_type == 'phone'
  end
end

app/controllers/from_methods_controller.rb
class FromMethodsController < ApplicationController
  authorize_resource

  def index
    @from_methods = FromMethod.order(:from_method)
    @title = "From Methods"
  end

  def new
    @from_method = FromMethod.new()
    @title = "Create New From Method"
  end

  def create
    @from_method = FromMethod.new(params[:from_method])
    if @from_method.save
      #from_method created
      #save the schools
      @from_method.school_ids = params[:schools]
      flash[:success] = "From Method successfully created."
      redirect_to @from_method
    else
      #there was an error
      @title = "Create New From Method"
      @from_method.from_method = params[:from_method][:from_method]
      render :new
    end
  end

  def show
    @from_method = FromMethod.find(params[:id])
    @title = "From Method Detail"
  end

  def update
    @from_method = FromMethod.find(params[:id])
    original_from_method = "#{params[:from_method][:from_method]}"
    if @from_method.update_attributes(params[:from_method])
      #update the schools as well
      @from_method.school_ids = params[:schools]
      flash[:success] = "From Method info updated."
      redirect_to @from_method
    else
      @title = "From Method Detail"
      @from_method.from_method = original_from_method
      render :show
    end
  end

  def destroy
    from_method = FromMethod.find(params[:id]).destroy
    flash[:notice] = "From Method '#{from_method.from_method}' deleted."
    redirect_to from_methods_path
  end

end

app/helpers/from_methods_helper.rb
module FromMethodsHelper
end

app/views/from_methods/_from_method_form.html.haml
= form_for(@from_method) do |f|
  = render 'shared/error_messages', :object => f.object
  %fieldset
    %legend Basic Info
    %div.form-field
      = f.label :from_method_type, 'Type', :class => "required"
      = f.select :from_method_type, options_for_select([['Email','email'],['Phone','phone']], @from_method.from_method_type)
    %div.form-field
      = f.label :from_method, "From Method", :class => 'required'
      = f.text_field :from_method, :value => (@from_method.from_method_type == 'phone' ? (!@from_method.from_method.humanize_phone_number ? @from_method.from_method : @from_method.from_method.humanize_phone_number) : @from_method.from_method)
  %fieldset
    %legend Schools
    %p.note Select the schools this From Method can be used at.
    %div.form-field
      = hidden_field_tag "schools[]", ''
      %ul.no-list-style
        - School.order(:name).each do |school|
          %li
            = check_box_tag "schools[]", school.id, @from_method.schools.include?(school)
            %strong= school.name
  %div.form-submit
    = f.submit "#{op} From Method"

app/views/from_methods/index.html.haml
%div#user-actions.round
  %p= link_to("Create New From Method", new_from_method_path)
%table
  %thead
    %tr
      %th From Method
      %th Type
  %tbody
    - @from_methods.each do |from_method|
      %tr
        %td= link_to (from_method.from_method_type == 'phone' ? from_method.from_method.humanize_phone_number : from_method.from_method), from_method
        %td= from_method.from_method_type.humanize

app/views/from_methods/new.html.haml
%p.back-link= link_to "Back", from_methods_path
= render 'from_method_form', :op => 'Create'

app/views/from_methods/show.html.haml
%p.back-link= link_to "Back", from_methods_path
= render 'from_method_form', :op => 'Edit'
%p.form-delete-link= link_to("Delete From Method", @from_method, :method => 'delete', :confirm => 'Are you sure you want to delete this From Method?  This can not be undone.')