config/routes.rb
LibrarySchedule::Application.routes.draw do

  root :to => "pages#home"

  resources :sessions, :only => [:new, :create, :destroy]
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
  match '/login/preauth', :to => 'sessions#preauth'

  scope '/admin' do
    resources :users, :except => [:edit]
    post '/users/:user_id', :to => "users#change_password"

    resources :schools, :except => [:edit]

    resources :from_methods, :except => [:edit]
  end

  scope '/manage' do
    resources :lists, :except => [:edit]
    resources :groups, :except => [:edit]
  end

  resources :recipients

  

end

app/views/layouts/_user_tools.haml
-if can? :view, :protected_content
  %div#home-button
    %li= link_to("Home", root_path)
%div#user-tools
  - if can? :view, :protected_content
    %li= (current_user.name.blank?) ? current_user.username : current_user.name
    %li= link_to("Logout", logout_path, :method => :delete)
  - else
    %li= link_to("Login", login_path)
  - if can? :manage, User
    %li= link_to("Users", users_path)

app/views/layouts/application.haml
!!! 5
%html
	%head
		%title= page_title
		= stylesheet_link_tag('blueprint/screen', :media => 'screen')
		= stylesheet_link_tag('blueprint/print', :media => 'print')
		= stylesheet_link_tag('main', :media => 'all')
		= stylesheet_link_tag('blackbird', :media => 'screen')
		= javascript_include_tag(:defaults)
		= javascript_include_tag('custom_scripts/blackbird')
		= yield :custom_scripts
		= csrf_meta_tag
	%body
		%div#outer-wrapper.round
			= render("layouts/user_tools")
			%div#page-content-wrapper
				- if(@title)
					%h1.title= @title
				- else
					%h1.title= page_title
				- flash.each do |key, value|
					%div{:class => "flash #{key}"}= value
				%div#page-content
					= yield
					= debug(params) if Rails.env.development?
				%div#footer